[[pages]]
path = "Home.py"
name = "ğŸ  Home"
icon = "ğŸ "

[[pages]]
path = "pages/1_2023_Dashboard.py"
name = "LaLiga 2023"
icon = "ğŸ“Š"

[[pages]]
path = "pages/2_2024_Dashboard.py"
name = "LaLiga 2024"
icon = "âš¡"

[[pages]]
path = "pages/3_About_Me.py"
name = "About"
icon = "ğŸ‘¤" 